// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/agents/:id": {
    params: {
      "id": string;
    };
  };
  "/system": {
    params: {};
  };
  "/brain": {
    params: {};
  };
  "/activity": {
    params: {};
  };
  "/diagnostics": {
    params: {};
  };
  "/templates/:id": {
    params: {
      "id": string;
    };
  };
  "/tools": {
    params: {};
  };
  "/skills": {
    params: {};
  };
  "/skills/:id/pack": {
    params: {
      "id": string;
    };
  };
  "/bridge": {
    params: {};
  };
  "/recall": {
    params: {};
  };
  "/changelog": {
    params: {};
  };
  "/architecture": {
    params: {};
  };
  "/design-system": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/intelligence": {
    params: {};
  };
  "/files": {
    params: {};
  };
  "/approvals": {
    params: {};
  };
  "/dreams": {
    params: {};
  };
  "/decomposition": {
    params: {};
  };
  "/decisions": {
    params: {};
  };
  "/sessions": {
    params: {};
  };
  "/evolution": {
    params: {};
  };
  "/msg-bus": {
    params: {};
  };
  "/env-tools": {
    params: {};
  };
  "/mcp": {
    params: {};
  };
  "/learnings": {
    params: {};
  };
  "/routing": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/dashboard" | "/agents/:id" | "/system" | "/brain" | "/activity" | "/diagnostics" | "/templates/:id" | "/tools" | "/skills" | "/skills/:id/pack" | "/bridge" | "/recall" | "/changelog" | "/architecture" | "/design-system" | "/settings" | "/intelligence" | "/files" | "/approvals" | "/dreams" | "/decomposition" | "/decisions" | "/sessions" | "/evolution" | "/msg-bus" | "/env-tools" | "/mcp" | "/learnings" | "/routing";
  };
  "routes/home-redirect.tsx": {
    id: "routes/home-redirect";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/dashboard" | "/agents/:id" | "/system" | "/brain" | "/activity" | "/diagnostics" | "/templates/:id" | "/tools" | "/skills" | "/skills/:id/pack" | "/bridge" | "/recall" | "/changelog" | "/architecture" | "/design-system" | "/settings" | "/intelligence" | "/files" | "/approvals" | "/dreams" | "/decomposition" | "/decisions" | "/sessions" | "/evolution" | "/msg-bus" | "/env-tools" | "/mcp" | "/learnings" | "/routing";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/dashboard";
  };
  "routes/agent-detail.tsx": {
    id: "routes/agent-detail";
    page: "/agents/:id";
  };
  "routes/system.tsx": {
    id: "routes/system";
    page: "/system";
  };
  "routes/brain.tsx": {
    id: "routes/brain";
    page: "/brain";
  };
  "routes/activity-redirect.tsx": {
    id: "routes/activity-redirect";
    page: "/activity";
  };
  "routes/diagnostics-redirect.tsx": {
    id: "routes/diagnostics-redirect";
    page: "/diagnostics";
  };
  "routes/template-detail.tsx": {
    id: "routes/template-detail";
    page: "/templates/:id";
  };
  "routes/tools.tsx": {
    id: "routes/tools";
    page: "/tools";
  };
  "routes/skills.tsx": {
    id: "routes/skills";
    page: "/skills";
  };
  "routes/skill-pack-explorer.tsx": {
    id: "routes/skill-pack-explorer";
    page: "/skills/:id/pack";
  };
  "routes/bridge.tsx": {
    id: "routes/bridge";
    page: "/bridge";
  };
  "routes/recall-redirect.tsx": {
    id: "routes/recall-redirect";
    page: "/recall";
  };
  "routes/changelog.tsx": {
    id: "routes/changelog";
    page: "/changelog";
  };
  "routes/architecture.tsx": {
    id: "routes/architecture";
    page: "/architecture";
  };
  "routes/design-system-lazy.tsx": {
    id: "routes/design-system-lazy";
    page: "/design-system";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/intelligence-redirect.tsx": {
    id: "routes/intelligence-redirect";
    page: "/intelligence";
  };
  "routes/files.tsx": {
    id: "routes/files";
    page: "/files";
  };
  "routes/approvals.tsx": {
    id: "routes/approvals";
    page: "/approvals";
  };
  "routes/dreams-redirect.tsx": {
    id: "routes/dreams-redirect";
    page: "/dreams";
  };
  "routes/decomposition.tsx": {
    id: "routes/decomposition";
    page: "/decomposition";
  };
  "routes/decisions.tsx": {
    id: "routes/decisions";
    page: "/decisions";
  };
  "routes/sessions-admin.tsx": {
    id: "routes/sessions-admin";
    page: "/sessions";
  };
  "routes/evolution.tsx": {
    id: "routes/evolution";
    page: "/evolution";
  };
  "routes/msg-bus.tsx": {
    id: "routes/msg-bus";
    page: "/msg-bus";
  };
  "routes/env-tools.tsx": {
    id: "routes/env-tools";
    page: "/env-tools";
  };
  "routes/mcp.tsx": {
    id: "routes/mcp";
    page: "/mcp";
  };
  "routes/learnings-redirect.tsx": {
    id: "routes/learnings-redirect";
    page: "/learnings";
  };
  "routes/routing.tsx": {
    id: "routes/routing";
    page: "/routing";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home-redirect": typeof import("./app/routes/home-redirect.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/agent-detail": typeof import("./app/routes/agent-detail.tsx");
  "routes/system": typeof import("./app/routes/system.tsx");
  "routes/brain": typeof import("./app/routes/brain.tsx");
  "routes/activity-redirect": typeof import("./app/routes/activity-redirect.tsx");
  "routes/diagnostics-redirect": typeof import("./app/routes/diagnostics-redirect.tsx");
  "routes/template-detail": typeof import("./app/routes/template-detail.tsx");
  "routes/tools": typeof import("./app/routes/tools.tsx");
  "routes/skills": typeof import("./app/routes/skills.tsx");
  "routes/skill-pack-explorer": typeof import("./app/routes/skill-pack-explorer.tsx");
  "routes/bridge": typeof import("./app/routes/bridge.tsx");
  "routes/recall-redirect": typeof import("./app/routes/recall-redirect.tsx");
  "routes/changelog": typeof import("./app/routes/changelog.tsx");
  "routes/architecture": typeof import("./app/routes/architecture.tsx");
  "routes/design-system-lazy": typeof import("./app/routes/design-system-lazy.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/intelligence-redirect": typeof import("./app/routes/intelligence-redirect.tsx");
  "routes/files": typeof import("./app/routes/files.tsx");
  "routes/approvals": typeof import("./app/routes/approvals.tsx");
  "routes/dreams-redirect": typeof import("./app/routes/dreams-redirect.tsx");
  "routes/decomposition": typeof import("./app/routes/decomposition.tsx");
  "routes/decisions": typeof import("./app/routes/decisions.tsx");
  "routes/sessions-admin": typeof import("./app/routes/sessions-admin.tsx");
  "routes/evolution": typeof import("./app/routes/evolution.tsx");
  "routes/msg-bus": typeof import("./app/routes/msg-bus.tsx");
  "routes/env-tools": typeof import("./app/routes/env-tools.tsx");
  "routes/mcp": typeof import("./app/routes/mcp.tsx");
  "routes/learnings-redirect": typeof import("./app/routes/learnings-redirect.tsx");
  "routes/routing": typeof import("./app/routes/routing.tsx");
};