#!/bin/bash
# Hook: PreCompact — serialize Porter state before context compaction
# Writes checkpoint so resuming sessions don't lose critical state (version, step, files)
set -euo pipefail

INPUT=$(cat)
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // "unknown"')
CWD=$(echo "$INPUT" | jq -r '.cwd // "/home/lobster/documents/porter"')
REASON=$(echo "$INPUT" | jq -r '.hook_config_location // "unknown"')
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
TIMESTAMP_SGT=$(TZ=Asia/Singapore date +"%Y-%m-%d %H:%M SGT")

PORTER="$CWD/porter.py"
CHECKPOINT="$CWD/tasks/checkpoint.md"

# Extract current version from porter.py
VERSION="unknown"
if [ -f "$PORTER" ]; then
  VERSION=$(head -2 "$PORTER" | grep -oP 'v\d+\.\d+\.\d+' || echo "unknown")
fi

# Get git status summary
GIT_STATUS=""
if cd "$CWD" 2>/dev/null && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  MODIFIED=$(git diff --name-only 2>/dev/null | head -5 | tr '\n' ', ')
  STAGED=$(git diff --cached --name-only 2>/dev/null | head -5 | tr '\n' ', ')
  BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
  LAST_COMMIT=$(git log --oneline -1 2>/dev/null || echo "unknown")
  GIT_STATUS="branch: $BRANCH | last: $LAST_COMMIT | modified: ${MODIFIED:-none} | staged: ${STAGED:-none}"
fi

# Get service status
SERVICE_STATUS=$(systemctl --user is-active porter 2>/dev/null || echo "unknown")

# Write checkpoint
mkdir -p "$(dirname "$CHECKPOINT")"
cat > "$CHECKPOINT" << EOF
# Checkpoint (auto-generated by PreCompact hook)
project: porter
version: $VERSION
timestamp: $TIMESTAMP_SGT
session_id: $SESSION_ID
status: compacted
service: $SERVICE_STATUS
git: $GIT_STATUS
next_action: Resume from where compaction interrupted. Check version $VERSION is current.
notes: Context was compacted. Read this file to restore state.
EOF

# Append to compaction log
LOG="$CWD/tasks/compaction-log.jsonl"
echo "{\"ts\":\"$TIMESTAMP\",\"session\":\"$SESSION_ID\",\"version\":\"$VERSION\",\"service\":\"$SERVICE_STATUS\"}" >> "$LOG"

exit 0
