import { FastifyInstance } from 'fastify';
import authV1Routes from './auth.js';
import projectV1Routes from './projects.js';
import collaboratorV1Routes, { collaboratorAcceptRoutes } from './collaborators.js';
import agentV1Routes from './agents.js';
import jobV1Routes from './jobs.js';
import wizardV1Routes from './wizard.js';
import healthV1Routes from './health.js';
import decisionV1Routes from './decisions.js';
import chatV1Routes from './chat.js';
import filesV1Routes from './files.js';
import preferencesV1Routes from './preferences.js';
import profileV1Routes from './profile.js';
import billingV1Routes from './billing.js';
import connectionsV1Routes from './connections.js';
import oauthGithubRoutes from './oauth-github.js';
import oauthGoogleRoutes from './oauth-google.js';
import webhookWhatsAppRoutes from './webhooks-whatsapp.js';
import errorV1Routes from './errors.js';
import contactV1Routes from './contacts.js';
import conversationV1Routes from './conversations.js';
import templateV1Routes from './templates.js';
import memoryV1Routes from './memory.js';
import bridgeV1Routes from './bridge.js';
import feedbackV1Routes from './feedback.js';
import tasksV1Routes from './tasks.js';
import { dispatchOutcomeRoutes } from './dispatch-outcome.js';
import sessionsV1Routes from './sessions.js';
import decompositionV1Routes from './decomposition.js';
import approvalV1Routes from './approvals.js';
import mailV1Routes from './mail.js';
import mailAdminV1Routes from './mail-admin.js';
import intellectV1Routes from './intellect.js';
// TODO: admin routes need import path fixes + PG conversion before enabling
// import adminV1Routes from './admin/index.js';

export default async function v1Routes(fastify: FastifyInstance) {
  fastify.register(authV1Routes, { prefix: '/auth' });
  fastify.register(projectV1Routes, { prefix: '/projects' });
  fastify.register(collaboratorV1Routes, { prefix: '/projects' });
  fastify.register(collaboratorAcceptRoutes, { prefix: '/collaborators' });
  fastify.register(agentV1Routes, { prefix: '/agents' });
  fastify.register(jobV1Routes, { prefix: '/jobs' });
  fastify.register(wizardV1Routes, { prefix: '/projects/wizard' });
  fastify.register(healthV1Routes, { prefix: '/health' });
  fastify.register(decisionV1Routes, { prefix: '/decisions' });
  fastify.register(chatV1Routes, { prefix: '/chat' });
  fastify.register(filesV1Routes, { prefix: '/files' });
  fastify.register(preferencesV1Routes, { prefix: '/preferences' });
  fastify.register(profileV1Routes, { prefix: '/profile' });
  fastify.register(billingV1Routes, { prefix: '/billing' });
  fastify.register(connectionsV1Routes, { prefix: '/connections' });
  fastify.register(oauthGithubRoutes, { prefix: '/oauth/github' });
  fastify.register(oauthGoogleRoutes, { prefix: '/oauth/google' });
  fastify.register(webhookWhatsAppRoutes, { prefix: '/webhooks/whatsapp' });
  fastify.register(errorV1Routes, { prefix: '/errors' });
  fastify.register(contactV1Routes, { prefix: '/contacts' });
  fastify.register(conversationV1Routes, { prefix: '/conversations' });
  fastify.register(templateV1Routes, { prefix: '/templates' });
  fastify.register(memoryV1Routes, { prefix: '/memory' });
  fastify.register(bridgeV1Routes, { prefix: '/bridge' });
  fastify.register(feedbackV1Routes, { prefix: '/feedback' });
  fastify.register(tasksV1Routes, { prefix: '/tasks' });
  fastify.register(dispatchOutcomeRoutes);
  fastify.register(sessionsV1Routes, { prefix: '/sessions' });
  fastify.register(decompositionV1Routes, { prefix: '/decomposition' });
  fastify.register(approvalV1Routes, { prefix: '/approvals' });
  fastify.register(mailV1Routes, { prefix: '/mail' });
  fastify.register(mailAdminV1Routes, { prefix: '/mail-admin' });
  fastify.register(intellectV1Routes, { prefix: '/intellect' });
  // fastify.register(adminV1Routes, { prefix: '/admin' });
}
