/**
 * gen-admin-release-info.ts — bake the ONE release truth into the admin SPA.
 *
 * The Porter admin (askporter.app) is a static build; relying on a live
 * /api/health/version fetch is fragile (askporter's /api proxy is an ephemeral
 * Caddy reload) and the admin's own package.json version drifts (was stuck at
 * 6.3.0). This stamps the BACKEND truth — version (backend/package.json) +
 * PORTER_RELEASES (the same curated feed the group announce uses) — into
 * app/lib/release-info.generated.ts at deploy, so the sidebar/footer version
 * and the changelog page both render from ONE source, in sync with what we
 * actually ship + announce. Run by admin/deploy.sh before `npm run build`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PORTER_RELEASES } from '../src/lib/porter-releases.js';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(resolve(here, '../package.json'), 'utf8')) as { version: string };
const out = resolve(here, '../../admin/frontend.archived/app/lib/release-info.generated.ts');

const banner = `// AUTO-GENERATED by backend/scripts/gen-admin-release-info.ts at deploy time.\n`
  + `// Do NOT edit. Source of truth: backend/package.json (version) +\n`
  + `// backend/src/lib/porter-releases.ts (PORTER_RELEASES — same feed as the group announce).\n`;

const body = `${banner}
export const PORTER_VERSION = ${JSON.stringify(pkg.version)};

export interface PorterRelease {
  version: string;
  date: string;
  title: string;
  bullets: string[];
}

export const PORTER_RELEASES: PorterRelease[] = ${JSON.stringify(PORTER_RELEASES, null, 2)};
`;

writeFileSync(out, body);
console.log(`[gen-admin-release-info] wrote ${out} — v${pkg.version}, ${PORTER_RELEASES.length} releases`);
