-- 0101_drop_dead_mail_forge_rpg.sql
--
-- Architecture-audit cleanup: drops tables backing three dead subsystems.
-- Generated by the cleanup pass on the `cleanup/dead-code-audit` branch.
-- NOT applied automatically — the operator applies this deliberately.
--
-- Verified zero live callers (grep across backend/src) before staging this drop:
--   1. Mail subsystem (migrate-mail-v1.ts) — disabled since Tranche 12, no route/
--      service reads or writes these tables. services/email.ts and
--      services/transactional-email.ts are UNRELATED and were kept (still wired
--      into external-dispatcher.ts / scheduler.ts / routes/v1/auth.ts).
--   2. Forge pipeline (schema.ts, previously created inline in migrate-consolidated.ts)
--      — the Forge feature is gone; no route or service references these tables.
--   3. RPG/Arena/battles gamification (schema.ts, created by migrate-rpg-v1.ts
--      alongside still-live tables session_registry/msg_bus_events/
--      intelligence_patterns, which are NOT touched here) — no route, service,
--      or frontend widget queries these tables.
--
-- Dropped in dependency order (children before parents / FK targets).

-- ── Mail subsystem (10 tables) ──────────────────────────────────────────────
DROP TABLE IF EXISTS mail_deliveries;
DROP TABLE IF EXISTS mail_learning_events;
DROP TABLE IF EXISTS mail_messages;
DROP TABLE IF EXISTS mail_threads;
DROP TABLE IF EXISTS mail_aliases;
DROP TABLE IF EXISTS newsletter_subscriptions;
DROP TABLE IF EXISTS newsletter_sources;
DROP TABLE IF EXISTS agent_mailboxes;
DROP TABLE IF EXISTS mailboxes;
DROP TABLE IF EXISTS mail_domains;

-- ── Forge pipeline (3 tables) ────────────────────────────────────────────────
DROP TABLE IF EXISTS forge_station_runs;
DROP TABLE IF EXISTS forge_pipeline;
DROP TABLE IF EXISTS forge_settings;

-- ── RPG / Arena / battles gamification (5 tables) ───────────────────────────
-- NOTE: does NOT touch session_registry, msg_bus_events, intelligence_patterns,
-- or the RPG columns added to agent_templates/template_skills by
-- migrate-rpg-v1.ts — those are out of scope (live or shared with live tables).
DROP TABLE IF EXISTS battle_rounds;
DROP TABLE IF EXISTS battle_judgments;
DROP TABLE IF EXISTS agent_bonds;
DROP TABLE IF EXISTS battles;
DROP TABLE IF EXISTS agent_rpg_stats;
