// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/users/:username": {
    params: {
      "username": string;
    };
  };
  "/email": {
    params: {};
  };
  "/billing": {
    params: {};
  };
  "/agents": {
    params: {};
  };
  "/agents/:id": {
    params: {
      "id": string;
    };
  };
  "/diagnostics": {
    params: {};
  };
  "/templates": {
    params: {};
  };
  "/models": {
    params: {};
  };
  "/porter": {
    params: {};
  };
  "/tools": {
    params: {};
  };
  "/skills": {
    params: {};
  };
  "/system": {
    params: {};
  };
  "/activity": {
    params: {};
  };
  "/changelog": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/users" | "/users/:username" | "/email" | "/billing" | "/agents" | "/agents/:id" | "/diagnostics" | "/templates" | "/models" | "/porter" | "/tools" | "/skills" | "/system" | "/activity" | "/changelog";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/users.tsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/user-detail.tsx": {
    id: "routes/user-detail";
    page: "/users/:username";
  };
  "routes/email.tsx": {
    id: "routes/email";
    page: "/email";
  };
  "routes/billing.tsx": {
    id: "routes/billing";
    page: "/billing";
  };
  "routes/agents.tsx": {
    id: "routes/agents";
    page: "/agents";
  };
  "routes/agent-detail.tsx": {
    id: "routes/agent-detail";
    page: "/agents/:id";
  };
  "routes/diagnostics.tsx": {
    id: "routes/diagnostics";
    page: "/diagnostics";
  };
  "routes/templates.tsx": {
    id: "routes/templates";
    page: "/templates";
  };
  "routes/models.tsx": {
    id: "routes/models";
    page: "/models";
  };
  "routes/porter.tsx": {
    id: "routes/porter";
    page: "/porter";
  };
  "routes/tools.tsx": {
    id: "routes/tools";
    page: "/tools";
  };
  "routes/skills.tsx": {
    id: "routes/skills";
    page: "/skills";
  };
  "routes/system.tsx": {
    id: "routes/system";
    page: "/system";
  };
  "routes/activity.tsx": {
    id: "routes/activity";
    page: "/activity";
  };
  "routes/changelog.tsx": {
    id: "routes/changelog";
    page: "/changelog";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/users": typeof import("./app/routes/users.tsx");
  "routes/user-detail": typeof import("./app/routes/user-detail.tsx");
  "routes/email": typeof import("./app/routes/email.tsx");
  "routes/billing": typeof import("./app/routes/billing.tsx");
  "routes/agents": typeof import("./app/routes/agents.tsx");
  "routes/agent-detail": typeof import("./app/routes/agent-detail.tsx");
  "routes/diagnostics": typeof import("./app/routes/diagnostics.tsx");
  "routes/templates": typeof import("./app/routes/templates.tsx");
  "routes/models": typeof import("./app/routes/models.tsx");
  "routes/porter": typeof import("./app/routes/porter.tsx");
  "routes/tools": typeof import("./app/routes/tools.tsx");
  "routes/skills": typeof import("./app/routes/skills.tsx");
  "routes/system": typeof import("./app/routes/system.tsx");
  "routes/activity": typeof import("./app/routes/activity.tsx");
  "routes/changelog": typeof import("./app/routes/changelog.tsx");
};