// AUTO-GENERATED by backend/scripts/gen-admin-release-info.ts at deploy time.
// Do NOT edit. Source of truth: backend/package.json (version) +
// backend/src/lib/porter-releases.ts (PORTER_RELEASES — same feed as the group announce).

export const PORTER_VERSION = "6.75.0";

export interface PorterRelease {
  version: string;
  date: string;
  title: string;
  bullets: string[];
}

export const PORTER_RELEASES: PorterRelease[] = [
  {
    "version": "6.75.0",
    "date": "2026-07-08",
    "title": "Admin version + changelog now tell the truth (and previews zoom)",
    "bullets": [
      "The Porter admin was showing a stale v6.3.0 in the sidebar/footer and a frozen changelog. Both now bake from the ONE backend release truth at deploy — the version matches what is actually running, and the changelog shows the same release notes the group announce uses. Also: the document preview now has zoom in/out/reset controls so an expanded PDF or image can be read at any size."
    ]
  },
  {
    "version": "6.74.0",
    "date": "2026-07-08",
    "title": "Release announces are now enforced, not optional",
    "bullets": [
      "The group release announcement is no longer something a session has to remember to run — Porter now re-asserts the announce for every project's current shipped version every 10 minutes, idempotently. If a release ever ships without its announce (any session, or none), Porter fills the gap automatically within minutes. The ceremony is structural now, not manual."
    ]
  },
  {
    "version": "6.73.0",
    "date": "2026-07-08",
    "title": "Release-kit R2 — Porter now audits release consistency",
    "bullets": [
      "Porter can now see, and flag drift in, how every project releases: a registry API (/api/admin/releases/*) reports each repo's release wiring — manifest present, hooks calling the shared kit, kit version current, version file present — and a drift audit gives one consistent|drift verdict across all projects. This is how Porter enforces one release standard everywhere."
    ]
  },
  {
    "version": "6.72.0",
    "date": "2026-07-08",
    "title": "Release-kit R1 — the shared release engine",
    "bullets": [
      "First piece of the unified release system: a shared release-kit in Porter (manifest schema + project registry + a porter-release CLI with a pre-commit gate and post-commit run sequence + the shared announce adapter). Groundwork so every project releases the exact same way and Porter can enforce it — not wired into any repo yet."
    ]
  },
  {
    "version": "6.71.0",
    "date": "2026-07-08",
    "title": "Porter now announces its own releases",
    "bullets": [
      "Porter releases now post to the group automatically the same way ymc.capital ones do — through the one shared announcer, fired from Porter’s own post-commit hook. No more separate manual step that could be forgotten."
    ]
  },
  {
    "version": "6.70.0",
    "date": "2026-07-08",
    "title": "Grok joined the model mesh",
    "bullets": [
      "Added the xAI Grok CLI (grok-4.5) as a fourth Bridge gateway alongside Claude, Codex and Antigravity — so Grok can be routed to directly and now sits on the design council."
    ]
  },
  {
    "version": "6.69.0",
    "date": "2026-07-08",
    "title": "Document Library — every app’s files, deduped and in sync",
    "bullets": [
      "New Document Library in the Porter admin: all of an app’s documents, organised the way the knowledge graph sees them (app → project → document), completely de-duplicated (one entry per unique file with every location tracked) and kept in sync so moved or deleted files drop off automatically. Personal material (passports, tax, personal financials) is never indexed. First app live: YMC with ~2,900 documents across 6 projects."
    ]
  }
];
