import { FastifyInstance } from 'fastify';
import healthRoutes from './health.js';
import bridgeRoutes from './bridge.js';
import diagnosticsRoutes from './diagnostics.js';
import modelsRoutes from './models.js';
import toolsRoutes from './tools.js';
import skillsRoutes from './skills.js';
import systemRoutes from './system.js';
import activityRoutes from './activity.js';
import settingsRoutes from './settings.js';
import chatRoutes from './chat.js';
import intelligenceRoutes from './intelligence.js';
import sessionsAdminRoutes from './sessions-admin.js';
import dreamsRoutes from './dreams.js';
import brainRoutes from './brain.js';
import msgBusRoutes from './msg-bus.js';
import envToolsRoutes from './env-tools.js';
import learningsRoutes from './learnings.js';
import routingRoutes from './routing.js';
import mcpRoutes from './mcp.js';
import reorgRoutes from './reorg.js';
import filesRoutes from './files.js';

export default async function adminRoutes(fastify: FastifyInstance) {
  fastify.register(healthRoutes, { prefix: '/health' });
  fastify.register(diagnosticsRoutes, { prefix: '/diagnostics' });
  fastify.register(modelsRoutes, { prefix: '/models' });
  fastify.register(bridgeRoutes, { prefix: '/bridge' });
  fastify.register(toolsRoutes, { prefix: '/tools' });
  fastify.register(skillsRoutes, { prefix: '/skills' });
  fastify.register(systemRoutes, { prefix: '/system' });
  fastify.register(activityRoutes, { prefix: '/activity' });
  fastify.register(settingsRoutes, { prefix: '/settings' });
  fastify.register(chatRoutes, { prefix: '/porter' });
  fastify.register(intelligenceRoutes, { prefix: '/intelligence' });
  fastify.register(sessionsAdminRoutes, { prefix: '/sessions' });
  fastify.register(dreamsRoutes, { prefix: '/dreams' });
  fastify.register(brainRoutes, { prefix: '/brain' });
  fastify.register(msgBusRoutes, { prefix: '/msg-bus' });
  fastify.register(envToolsRoutes, { prefix: '/env-tools' });
  fastify.register(learningsRoutes, { prefix: '/learnings' });
  fastify.register(routingRoutes, { prefix: '/routing' });
  fastify.register(mcpRoutes, { prefix: '/mcp' });
  fastify.register(reorgRoutes, { prefix: '/reorg' });
  fastify.register(filesRoutes, { prefix: '/files' });
}
