import { FastifyInstance } from 'fastify';
import healthRoutes from './health.js';
import usersRoutes from './users.js';
import emailRoutes from './email.js';
import billingRoutes from './billing.js';
import bridgeRoutes from './bridge.js';
import agentsRoutes from './agents.js';
import diagnosticsRoutes from './diagnostics.js';
import templatesRoutes from './templates.js';
import modelsRoutes from './models.js';
import forgeRoutes from './forge.js';
import toolsRoutes from './tools.js';
import skillsRoutes from './skills.js';
import systemRoutes from './system.js';
import activityRoutes from './activity.js';
import settingsRoutes from './settings.js';
import chatRoutes from './chat.js';
import customersRoutes from './customers.js';
import intelligenceRoutes from './intelligence.js';
import jobsRoutes from '../v1/admin/jobs.js';
import watchersRoutes from '../v1/admin/watchers.js';
import mailAdminRoutes from '../v1/mail-admin.js';

export default async function adminRoutes(fastify: FastifyInstance) {
  fastify.register(healthRoutes, { prefix: '/health' });
  fastify.register(usersRoutes, { prefix: '/users' });
  fastify.register(customersRoutes, { prefix: '/customers' });
  fastify.register(emailRoutes, { prefix: '/email' });
  fastify.register(billingRoutes, { prefix: '/billing' });
  fastify.register(agentsRoutes, { prefix: '/agents' });
  fastify.register(diagnosticsRoutes, { prefix: '/diagnostics' });
  fastify.register(templatesRoutes, { prefix: '/templates' });
  fastify.register(modelsRoutes, { prefix: '/models' });
  fastify.register(bridgeRoutes, { prefix: '/bridge' });
  fastify.register(forgeRoutes, { prefix: '/forge' });
  fastify.register(toolsRoutes, { prefix: '/tools' });
  fastify.register(skillsRoutes, { prefix: '/skills' });
  fastify.register(systemRoutes, { prefix: '/system' });
  fastify.register(activityRoutes, { prefix: '/activity' });
  fastify.register(settingsRoutes, { prefix: '/settings' });
  fastify.register(chatRoutes, { prefix: '/porter' });
  fastify.register(intelligenceRoutes, { prefix: '/intelligence' });
  fastify.register(jobsRoutes, { prefix: '/jobs' });
  fastify.register(watchersRoutes, { prefix: '/watchers' });
  fastify.register(mailAdminRoutes, { prefix: '/mail' });
}
