import { type RouteConfig, index, layout, route } from "@react-router/dev/routes"

export default [
  index("routes/home-redirect.tsx"),
  route("login", "routes/login.tsx"),

  // All authenticated routes share one AdminShell instance (no remount on navigation)
  layout("routes/layout.tsx", [
    route("dashboard", "routes/home.tsx"),
    route("email", "routes/email.tsx"),
    route("forge", "routes/forge.tsx"),
    route("agents/:id", "routes/agent-detail.tsx"),
    route("system", "routes/system.tsx"),
    route("brain", "routes/brain.tsx"),
    route("activity", "routes/activity-redirect.tsx"),
    route("diagnostics", "routes/diagnostics-redirect.tsx"),
    route("templates/:id", "routes/template-detail.tsx"),
    route("tools", "routes/tools.tsx"),
    route("skills", "routes/skills.tsx"),
    route("skills/:id/pack", "routes/skill-pack-explorer.tsx"),
    route("bridge", "routes/bridge.tsx"),
    route("recall", "routes/recall-redirect.tsx"),
    route("changelog", "routes/changelog.tsx"),
    route("architecture", "routes/architecture.tsx"),
    route("design-system", "routes/design-system-lazy.tsx"),
    route("settings", "routes/settings.tsx"),
    route("intelligence", "routes/intelligence-redirect.tsx"),
    route("files", "routes/files.tsx"),
    route("approvals", "routes/approvals.tsx"),
    route("dreams", "routes/dreams-redirect.tsx"),
    route("decomposition", "routes/decomposition.tsx"),
    route("decisions", "routes/decisions.tsx"),
    route("sessions", "routes/sessions-admin.tsx"),
    route("evolution", "routes/evolution.tsx"),
    route("msg-bus", "routes/msg-bus.tsx"),
    route("env-tools", "routes/env-tools.tsx"),
    route("learnings", "routes/learnings-redirect.tsx"),
    route("skill-feedback", "routes/skill-feedback.tsx"),
    route("routing", "routes/routing.tsx"),
  ]),
] satisfies RouteConfig
